__default__:
  cores: '{params.threads}'
  mem: '{params.mem}'
  logout: '{wildcards.outdir}/job_logs/{wildcards.mouse}/{wildcards.cp}/{rule}.out'
  logerror: '{wildcards.outdir}/job_logs/{wildcards.mouse}/{wildcards.cp}/{rule}.err'
  runtime: 336:00:00

runEvotracer:
    logout: '{wildcards.outdir}/job_logs/{wildcards.mouse}/{rule}.out'
    logerror: '{wildcards.outdir}/job_logs/{wildcards.mouse}/{rule}.err'

plotEvotracerResults:
    logout: '{wildcards.outdir}/job_logs/{wildcards.mouse}/{rule}.out'
    logerror: '{wildcards.outdir}/job_logs/{wildcards.mouse}/{rule}.err'

splitCPs:
    logout: '{wildcards.outdir}/job_logs/{wildcards.mouse}/{rule}.out'
    logerror: '{wildcards.outdir}/job_logs/{wildcards.mouse}/{rule}.err'

plotCpSizeBars:
    logout: '{wildcards.outdir}/job_logs/{wildcards.mouse}/{rule}.out'
    logerror: '{wildcards.outdir}/job_logs/{wildcards.mouse}/{rule}.err'

prepMachina:
    logout: '{wildcards.outdir}/job_logs/{wildcards.mouse}/{rule}.out'
    logerror: '{wildcards.outdir}/job_logs/{wildcards.mouse}/{rule}.err'

getOverallTransitionMatrixPerMouse:
    logout: '{wildcards.outdir}/job_logs/{wildcards.mouse}/{rule}.out'
    logerror: '{wildcards.outdir}/job_logs/{wildcards.mouse}/{rule}.err'

plotOverallTransitionMatrixPerMouse:
    logout: '{wildcards.outdir}/job_logs/{wildcards.mouse}/{rule}.out'
    logerror: '{wildcards.outdir}/job_logs/{wildcards.mouse}/{rule}.err'

getOverallSeedingTopologyPerMouse:
    logout: '{wildcards.outdir}/job_logs/{wildcards.mouse}/{rule}.out'
    logerror: '{wildcards.outdir}/job_logs/{wildcards.mouse}/{rule}.err'

plotOverallSeedingTopologyPerMouse:
    logout: '{wildcards.outdir}/job_logs/{wildcards.mouse}/{rule}.out'
    logerror: '{wildcards.outdir}/job_logs/{wildcards.mouse}/{rule}.err'