
# directory for input fastq files
fastqPath: /grid/siepel/home/hassett/snakemake_evotracer_machina/data/serio_11_24_25

# directory for output
outdir: /grid/siepel/home/staklins/projects/crispr_barcode/results/ryan_prostate_2p_2pr/analysis_on_11_24_25_serio_data


# evotracer parameters
asvThreshold: 3

# # evotracer parameters for BC10v0
# ref_name: "BC10v0"
# ref_seq: "TCTACACGCGCGTTCAACCGAGGAAAACTACACACACGTTCAACCACGGTTTTTTACACACGCATTCAACCACGGACTGCTACACACGCACTCAACCGTGGATATTTACATACTCGTTCAACCGTGGATTGTTACACCCGCGTTCAACCAGGGTCAGATACACCCACGTTCAACCGTGGTACTATACTCGGGCATTCAACCGCGGCTTTCTGCACACGCCTACAACCGCGGAACTATACACGTGCATTCACCCGTGGATC"
# ref_flank_right: "CCCGTGGATC"

# evotracer parameters for BC10v2
ref_name: "BC10v2"
ref_seq: "TCTACACGCGCGTTCAACCGAGGAAAACTACACACGCATTCAACCACGGTTTATTACACGCACATTCAACCGTGGACTGCTACACACGCGCTCAACCACGGATATTTACGCACACGTTCAACCGCGGATTGTTACACCCGCATTCAACCGAGGTCACCTACACCCGCACTCAACCGGGGTACGCGACACGTGCGATCAACCGAGGCTTACTACCCGCACGTTCAACTGGGGAACACTGCACGCGAGTTCGACCGGGGATC"
ref_flank_right: "ACCGGGGATC"

# same for both bc10v0 and bc10v2
ref_flank_left: "TCTAC"
ref_cut_sites: "17,43,69,95,121,147,173,199,225,251"
ref_border_sites: "1,26,52,78,104,130,156,182,208,234"


# machina parameters
primaryTissue:
  MMUS1834: BDR
  MMUS3012: BDR
  MMUS3011: BDR
  MMUS3010: BDR
  MMUS1910: BDR
  MMUS1957: BDR
  MMUS1782: BDR
  MMUS7288: BDR
  MMUS7280: BDR
  MMUS7235: BDR
  MMUS7182: BDR
  MMUS7200: BDR
  MMUS7235: BDR
  MMUS7239: BDR
  MMUS7293: BDR
  MMUS7317: PRL
  MMUS7323: PRL
  MMUS7351: PRL
  MMUS7354: PRL
  MMUS7358: PRL
  MMUS7438: PRL
  MMUS7439: PRL
  MMUS7440: PRL
  MMUS7447: PRL
  MMUS7490: PRL
  MMUS7507: PRL
  MMUS7487: PRL


# paths to scripts and executables
scripts: /grid/siepel/home/staklins/projects/crispr_barcode/snakemake_evotracer_machina/scripts
envs: /grid/siepel/home/staklins/projects/crispr_barcode/snakemake_evotracer_machina/envs
